name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: "x64"
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pylint mypy pytest

    - name: Run linting
      run: pylint quake_api --disable=C0114,C0115,C0116,C0301,E0402 # Pointing to quake_api

    - name: Run type checks
      run: mypy quake_api

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app .
