name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: "x64"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pylint pytest

    - name: Run linting
      run: pylint quake_api quake_parser tests --disable=C0114,C0115,C0116,C0301,E0402
      # Updated to lint the new directories

    - name: Run tests
      run: pytest
      # Ensure your tests directory is included, adjust if necessary

    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app .
      # Confirm Dockerfile path or build context is correct if needed
