name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pylint src/  # Adjust this if your code is in a different directory

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t my-fastapi-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-fastapi-app ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
